name: CI
'on':
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6
        name: Check depps

      - run: git clean -xfd
        name: Clean workspace

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
        name: Setup node

      - run: npm i --legacy-peer-deps
        name: Install dependencies

      - run: npx prisma generate
        shell: cmd
        name: Generate prisma client

      - run: npm run format
        name: Format code

      - run: npm run lint
        name: Lint code

      - run: npm run test
        name: Run tests